google:
  cloud:
    pubsub:
      subscriptions:
        integration-messages:
          subscription: integration-messages-customer-svc-sub
          thread-count: 4
          max-messages: 50
          max-request-size-mb: 32
          enabled: ${GCP_INTEGRATION_MESSAGES_SUB_ENABLED:true}

sentry:
  debug: true
  dsn: ${SENTRY_DNS}
  environment: develop
  send-default-pii: true
  tracesSampleRate: 0.0
  sampleRate: 0.0
  logging:
    enabled: false
    minimum-event-level: error
  exception-resolver-order: -2147483647
